### PR TITLE
HabitUp app level class and unit tests

### PR DESCRIPTION
**Pull request by tyheise**
Not 100% sure if my tests for saving and loading are thorough enough. I operated under the assumption that the filename for the local file would be hard-coded so no errors on loading would occur.

### CODE REVIEW

**Comment by gojeffcho** [comment]
@tyheise I think this model shows us that our conceptualization of HabitUp is incorrect; for example, HabitUp shouldn't be concerned with doing UserAccount stuff.  I think what we need is a separate UserAccountList container which has all of those functions, and the HabitUp instance just contains a UserAccountList.  Do you think you can model one off of HabitEventList, using the kinds of interactions you've modeled here, so that we have separation between the app-level HabitUp stuff (authentication, load/store, etc) and the UserAccount stuff?

**Comment by tyheise** [comment]
@gojeffcho Just to make sure I understand, when you say "HabitUp shouldn't be concerned with doing UserAccount stuff" are you referring to searching the UserAccounts and adding UserAccounts to it's array list?

**Comment by gojeffcho** [comment]
@tyheise Right.  It should have a UserAccountList, but the operations on the UserAccountList itself should be done via the UserAccountList object, e.g. HabitUp.getUserAccountList().addUser(user).  Anything to do with the UserAccounts should be localized and separated to those containers/controllers, because it makes no sense for user stuff to be happening at the app level, if I'm making sense?

**Comment by tyheise** [comment]
Makes perfect sense, I'll start implementing the Account container right now.

**Comment by tyheise** [comment]
I added the new container and tests for it. I kept the method for UserAccountList that returns an ArrayList of UserAccounts representing the UserAccountList object but I'm not sure if we will actually need it.

**Pull request merged**
