### PR TITLE
Unit test/habitevent

### PR DESCRIPTION
**Pull request by acsyl**
I am trying to use bytearray to compare the size. When size is greater than  65536 bytes, I just compress the image until it is smaller than 65536 bytes. Not hundred percent sure it works.

### CODE REVIEW

**Comment by gojeffcho** [comment]
@acsyl: I think comment on HabitEvent has a length restriction (check Use Cases) that we need to check, so it might need to throw something.  

Date also requires boundary checking - it cannot be before today's date, and if changed, it cannot be before the initially set date.

I think HabitEvents also need to store what Habit they belong to as a two-way relationship (Habits store HabitEventLists, but I think each Habit also needs to reference back to the owning Habit; I forget why off the top of my head, though, so maybe I'm wrong there).

What is the intended construction method?  Instance a blank HabitEvent, then use the setters to write data to it?  I think we need at least a constructor that restricts the required members, e.g. date, and initializes other members (e.g. default comment blank, default location null, etc.) so that we have better predictability and control.

**Comment by gojeffcho** [comment]
Oh, and sorry - HabitEvent requires a copy constructor as well, due to functionality implemented in HabitEventList.

**Comment by acsyl** [comment]
I will try to fix these problems.

**Comment by gojeffcho** [comment]
@acsyl: I would give it a copy constructor and some comment lines in constructors and setter methods that boundary checking will be done and an exception thrown if invalid (and add throws WhateverException to the signature) and I think it's good to go!

**Comment by acsyl** [comment]
I have given it a constructor and I do not know why I missed it which was a stupid mistake. I have also written a test for length and date restriction.

**Pull request merged**
