### PR TITLE
Classes implementation for P3

### PR DESCRIPTION
**Pull request by gojeffcho**
UserAccount model and UserAccountTest JUnit testsuite
HabitEventList model and HabitEventListTest JUnit testsuite

The code as supplies causes no errors in Android Studio.

### CODE REVIEW

**Comment by sharibarboza** [comment]
How are we implementing the sort for habit events? Will this be done through the ElasticSearch or the main model?

Also, will UserAccount have a method to update attribute values?

**Comment by sharibarboza** [comment]
Or will it just get the Attributes object directly and then use the Attribute methods?

**Comment by gojeffcho** [comment]
@sharibarboza: I was thinking the sort would be done by (or after) the search, but I think we could maybe implement a sorting method on the HabitEventList as well, since it makes sense programmatically to have it there?

UserAccount shouldn't have implementation for Attributes, since that should and would be handled by the Attributes themselves.  UserAccountX.getAttributes().whateverUpdateFunction() should be the preferred way to do this.

**Comment by sharibarboza** [comment]
Ok, everything looks good then.

**Pull request merged**
