### PR TITLE
Attributes

### PR DESCRIPTION
**Pull request by sharibarboza**
Added Attributes Model with attributes test suite.

### CODE REVIEW

**Comment by gojeffcho** [comment]
@sharibarboza: Can we make the Attributes names array public or add a getter method for it, so that we can always pull it from wherever?  This would be used for populating, e.g. the dropdown list of what Attribute to link a HabitEvent to, or your initialization testcase.

I think it might be worth changing "Intelligence" to "Mental", "Strength" to "Physical".  For example, endurance running might fit "Physical" better than "Strength", and I think there are things that can be done in the knowledge/practice domain that might not fit "Intelligence" so closely but could fit "Mental".  Thoughts?

**Comment by sharibarboza** [comment]
Yeah, actually I agree and think it's better to return the list of names. I'll make a getter method for them.

**Comment by gojeffcho** [comment]
@sharibarboza: I think this looks good!  This gives no errors in Android Studio (obviously the tests won't validate, but syntax-wise, everything is kosher)?

**Comment by sharibarboza** [comment]
Yeah, I ran it in Android Studio and it says all 3 tests passed. Is there a way to show the results here?

**Comment by gojeffcho** [comment]
Approved for pull as far as I'm concerned!  Leaving open for additional review as needed.

**Comment by sharibarboza** [comment]
Should I change to be using this keyword like ```this.attributeMap``` inside the methods? For some reason, I forgot for those ones.

**Pull request merged**
