### PR TITLE
Habit class and tests

### PR DESCRIPTION
**Pull request by alido8592**
I don’t know if I approached the schedule right by making it a series of Boolean entries. I was thinking of the checkbox implication when I did that. Let me know what a better application for it would be

### CODE REVIEW

**Comment by sharibarboza** [comment]
What is the relationship between Habits and attributes? I thought the User can use his XP to increase any attribute level by a certain number of points? But I did not know that Habits are associated with a certain attribute. Or maybe I thought wrong about the way we're particularly implementing it? @gojeffcho can you correct me on this one?

**Comment by gojeffcho** [comment]
@alido8592 HabitEvents should be a HabitEventList container instead of an ArrayList<HabitEvent>

The attribute associated with a HabitEvent shouldn't be an Attributes object (which is the storage for the attribute levels of a UserAccount) but a field which corresponds to one named Attribute on an Attribute object - @sharibarboza is it worth turning each attribute into an enum instead of a string?

For Booleans for days - we might want to start with index 0 as Sunday, if the Calendar API in Android starts the week on Sundays, which it most likely does.

Schedule also needs to have at least one set, so that checking needs to be done  (these don't have to be currently implemented since all methods can be placeholder blanks, but at least put in // TODO: comment lines so we don't think something is fully implemented and forget to add it later)

I think we'll end up needing a separate updateSchedule() function for when it gets edited - if a schedule gets changed, we need to revisit the way we calculate the stats and essentially "store" the stats up to current so that it doesn't mess with future stats-calculation.  We haven't worked this out yet, so I wouldn't worry about implementation, just put in an empty function to signify that we've thought of this eventuality

You have a Habit constructor which takes all parameters and constructs a Habit without bounds checking, but you also have setters which do (commented, future-implementation) bounds checking, which is conflicting in terms of implementation.

In your unique name testcase, I believe this still works if Java has immutable Strings, but I would only use one variable with "name" on it.  This also depends on how we do equality checking on set, which should be done lexicographically if that is not the default behavior for Java String == String cmp.

Why do the testcases have name and habitName?  We should be testing for boundary checking both at instantiation and on edit (manual call to mutator)

**Comment by gojeffcho** [comment]
@sharibarboza I believe our intent is that each Habit (type) is associated with a specific Attribute.  So for example, "Go to the gym" would be associated with Physical (if the user so sets it), "Study" would be associated with Mental, etc.  Then every time the user completes that activity, they gain points toward those Attributes.  XP affects level, an overall indicator of progress, and Attributes are more of an indicator of how well-rounded the user is?

**Comment by sharibarboza** [comment]
Okay, thanks for clearing that up.

**Comment by sharibarboza** [comment]
@gojeffcho do you mean access an attribute value by an index instead of the name?

**Comment by gojeffcho** [comment]
@sharibarboza I guess?  Less so by index, since it can still be an unordered hashmap, but it would flatten the Strings down into ints at compile-time.  I guess I'm mostly thinking about if we would ever update or change Attributes down the line, but it shouldn't be an issue using literal strings (especially since they're static final) as long as we're guaranteed that the structure will never change.

**Comment by sharibarboza** [comment]
I see what you're saying. Since the attribute names are not an input from the user and something set by us, I would see why we wouldn't need the strings, if they're going to be converted to ints anyways. In that case, if we were to use enum, would array list be a better data structure than hashmap to hold the attributes?

**Comment by alido8592** [comment]
@gojeffcho oh oops, I totally missed the unique name on the TODO for the constructor. 

so for the Habit's attribute, would that just be a String then just as in Attributes attributeNames?

re: test cases - right right sorry forgot to clean up the test cases as I wanted to get them out LOL I'll get rid of those habitNames

**Comment by gojeffcho** [comment]
I'm not gonna lie, I didn't re-read everything all over again, but from the little bit that I did re-skim, I think this is good to go now.

**Pull request merged**
